### PR TITLE
Implement Mustermann::Grape

### PR DESCRIPTION
**Pull request by namusyaka**
@rkh I'd like to use Mustermann in the new router of Grape.
I've already implemented [this class in mustermann19](https://github.com/namusyaka/mustermann19/blob/19support/lib/mustermann/grape.rb).

Could you merge this into your central repo?

### CODE REVIEW

**Comment by rkh** [comment]
:+1: looks good. Will have to figure out what's up with the travis setup.

I'd like to give you a commit bit. We'll also move Mustermann from being a personal project of mine to being part for the Sinatra org soon.

**Comment by namusyaka** [comment]
Thank you for your kindness!
I'd like to collaborate to maintenance!

**Comment by namusyaka** [comment]
@rkh I've just fixed some points. Also, [this hansi pull request](https://github.com/rkh/hansi/pull/1) will fix the error of ruby-2.2.
Could you merge the pull request?

**Comment by namusyaka** [comment]
@rkh Fixed. All tests have been successful now.

**Comment by namusyaka** [comment]
Thank you for merging! :)

**Pull request merged**
